thresholds:
  temperature: 8.0
  humidity: 50.0

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus" # Expose health, info, and prometheus endpoints
  endpoint:
    health:
      show-details: always # Show full health details
