apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # Default scrape interval
    scrape_configs:
      - job_name: 'spring-app'
        metrics_path: '/actuator/prometheus' # Path for Spring Boot Prometheus metrics
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          # Scrape only pods matching the service name 'food-quality-app-service'
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: food-quality-app # Assuming your service/pods have a label app=food-quality-app
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http # Assuming your service port is named 'http' or matches the app's port
          # Alternatively, use static config if service discovery is not needed/set up:
          # static_configs:
          #   - targets: ['food-quality-app-service.default.svc.cluster.local:8080'] # Replace with your actual service DNS and port
