apiVersion: v1
kind: Service
metadata:
  name: food-quality-dashboard
  labels:
    app: food-quality-dashboard
spec:
  type: ClusterIP # change to LoadBalancer if needed
  selector:
    app: food-quality-dashboard
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
